/**
 * HTML escaping utilities for Plane issue description construction.
 *
 * Prevents stored XSS when user-controlled strings (operator message, LLM
 * synthesis) are interpolated into description_html sent to Plane.
 *
 * Refs: docs/specs/walter-council-v2.md
 * Reviewer round 1 finding: stored XSS in spin-spec via Plane (BLOCKER 4).
 */

import type { SynthesisResult } from "@/server/council/history";

/**
 * Escape a string for safe interpolation into an HTML context.
 */
export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Build the HTML issue description for Plane, escaping all user-controlled
 * and LLM-sourced strings before interpolation.
 */
export function buildIssueDescription(
  originalMessage: string,
  synthesis: SynthesisResult,
  sessionId: string
): string {
  const safeMessage = escapeHtml(originalMessage);
  const safeSummary = escapeHtml(synthesis.summary);
  const safeRecommendedPath = escapeHtml(synthesis.recommended_path);

  const convergenceItems =
    synthesis.convergences.length > 0
      ? `<ul>${synthesis.convergences.map((c) => `<li>${escapeHtml(c)}</li>`).join("")}</ul>`
      : "";

  const disagreementItems =
    synthesis.disagreements.length > 0
      ? `<ul>${synthesis.disagreements.map((d) => `<li>${escapeHtml(d)}</li>`).join("")}</ul>`
      : "";

  const nextStepItems =
    synthesis.next_steps.length > 0
      ? `<ol>${synthesis.next_steps.map((s) => `<li>${escapeHtml(s)}</li>`).join("")}</ol>`
      : "";

  const parts: string[] = [
    `<h2>Council Deliberation Summary</h2>`,
    `<p><strong>Original question</strong>: ${safeMessage}</p>`,
    `<p><strong>Summary</strong>: ${safeSummary}</p>`,
  ];

  if (convergenceItems) {
    parts.push(`<p><strong>Convergences</strong>:</p>${convergenceItems}`);
  }

  if (disagreementItems) {
    parts.push(`<p><strong>Open disagreements</strong>:</p>${disagreementItems}`);
  }

  parts.push(`<p><strong>Recommended path</strong>: ${safeRecommendedPath}</p>`);

  if (nextStepItems) {
    parts.push(`<p><strong>Next steps</strong>:</p>${nextStepItems}`);
  }

  parts.push(
    `<hr/>`,
    `<p><em>Generated by Walter Council Control Tower — session ${escapeHtml(sessionId)}</em></p>`
  );

  return parts.join("\n");
}
