#!/usr/bin/env bats
# tests/cli/doctor-antigravity.bats
#
# Covers `walter-os doctor --antigravity` — probes the project-local
# Antigravity adapter at <cwd>/.agent/rules/walter-os.md and warns
# about GEMINI.md precedence conflicts.
#
# Spec: docs/specs/antigravity-adapter.md
# Closes #190.

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
  WALTER_OS_BIN="$REPO_ROOT/bin/walter-os"
  export WALTER_OS_HOME="$REPO_ROOT"
  FAKE_REPO="$BATS_TEST_TMPDIR/fake-repo"
  mkdir -p "$FAKE_REPO"
}

_run_probe() {
  (cd "$FAKE_REPO" && bash "$WALTER_OS_BIN" doctor --antigravity)
}

_create_agents() {
  cat > "$FAKE_REPO/AGENTS.md" <<'EOF'
# AGENTS.md — fixture

## Universal disciplines

Test fixture for doctor --antigravity.
EOF
}

_create_adapter_with_sha() {
  # Compute the sha of the current AGENTS.md and embed it in the adapter.
  local sha
  if command -v sha256sum >/dev/null 2>&1; then
    sha="$(sha256sum "$FAKE_REPO/AGENTS.md" | awk '{print $1}')"
  else
    sha="$(shasum -a 256 "$FAKE_REPO/AGENTS.md" | awk '{print $1}')"
  fi
  mkdir -p "$FAKE_REPO/.agent/rules"
  cat > "$FAKE_REPO/.agent/rules/walter-os.md" <<EOF
<!-- Generated by walter-os install.sh --antigravity-rules -->

# Walter-OS — Antigravity rules (derived from AGENTS.md)

$(cat "$FAKE_REPO/AGENTS.md")

<!-- agents-md-sha256: ${sha} -->
EOF
}

# ---------------------------------------------------------------------------
# AC-6: four probe states
# ---------------------------------------------------------------------------

@test "AC-6: STATUS: NOT_GENERATED when adapter file is absent" {
  _create_agents
  run _run_probe
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"NOT_GENERATED"* ]]
  [[ "$output" == *".agent/rules/walter-os.md"* ]]
  [[ "$output" == *"install.sh --antigravity-rules"* ]]
}

@test "AC-6: STATUS: PASS when adapter file matches current AGENTS.md SHA" {
  _create_agents
  _create_adapter_with_sha
  run _run_probe
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"PASS"* ]]
  [[ "$output" == *"Adapter is current"* ]]
}

@test "AC-6: STATUS: STALE when AGENTS.md changed after adapter was generated" {
  _create_agents
  _create_adapter_with_sha
  # Mutate AGENTS.md AFTER the adapter was sealed.
  echo "## EXTRA SECTION (post-adapter)" >> "$FAKE_REPO/AGENTS.md"
  run _run_probe
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"STALE"* ]]
  [[ "$output" == *"recorded"* ]]
  [[ "$output" == *"current"* ]]
}

@test "AC-6: STATUS: WARN when adapter exists but AGENTS.md is missing" {
  _create_agents
  _create_adapter_with_sha
  # Remove the source of truth AFTER the adapter was generated.
  rm -f "$FAKE_REPO/AGENTS.md"
  run _run_probe
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"WARN"* ]]
  [[ "$output" == *"no AGENTS.md"* ]] || [[ "$output" == *"AGENTS.md"* ]]
}

@test "AC-6: WARN on GEMINI.md precedence collision (even when adapter is PASS)" {
  _create_agents
  _create_adapter_with_sha
  echo "# stray GEMINI.md" > "$FAKE_REPO/GEMINI.md"
  run _run_probe
  [[ "$status" -eq 0 ]]
  # Both the GEMINI warning AND the PASS status should appear.
  [[ "$output" == *"GEMINI.md"* ]]
  [[ "$output" == *"precedence"* ]] || [[ "$output" == *"shadow"* ]]
  [[ "$output" == *"PASS"* ]]
}

# ---------------------------------------------------------------------------
# Header + scoping invariants
# ---------------------------------------------------------------------------

@test "probe header names the Antigravity adapter (not Cursor / Lite)" {
  _create_agents
  run _run_probe
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"Antigravity adapter probe"* ]]
}

@test "probe is project-scoped — checks <cwd>/.agent, not ~/.agent" {
  _create_agents
  run _run_probe
  [[ "$status" -eq 0 ]]
  # The reported path must include the FAKE_REPO prefix.
  [[ "$output" == *"$FAKE_REPO/.agent/rules/walter-os.md"* ]]
  # AND must NOT mention $HOME/.agent.
  [[ "$output" != *"$HOME/.agent"* ]]
}
