#!/usr/bin/env bash
# scripts/walter/lib/providers/apply.sh
#
# Writes providers.yaml and prints the Ollama post-config note.
# Sourced by providers.sh wizard.

# write_providers_yaml <llm> <pm> <git> <secrets> <analytics> <search> <embeddings> <output_path>
#
# Writes the canonical providers.yaml. Idempotent: same inputs produce the
# same file (deterministic YAML, no timestamps).
write_providers_yaml() {
  local llm="$1"
  local pm="$2"
  local git_provider="$3"
  local secrets_provider="$4"
  local analytics="$5"
  local search="$6"
  local embeddings="$7"
  local out_path="${8:-${HOME}/.config/walter-os/providers.yaml}"

  mkdir -p "$(dirname "$out_path")"

  # Write deterministically so re-runs with identical inputs are byte-for-byte
  # identical (no timestamp, sorted keys match template order).
  cat > "$out_path" << YAML
# providers.yaml — Walter-OS provider choices
# Generated by: walter providers configure
# Edit via: walter providers configure (not manually)
llm: ${llm}
project_management: ${pm}
git: ${git_provider}
secrets: ${secrets_provider}
web_analytics: ${analytics}
search: ${search}
embeddings: ${embeddings}
YAML
}

# print_ollama_note
# Prints the post-config note for Ollama/nomic-embed-text. [AC-6]
print_ollama_note() {
  cat << 'NOTE'
Post-config note for Ollama embeddings:
  Ollama must be running at OLLAMA_BASE_URL with nomic-embed-text pulled.
  Verify: `ollama list | grep nomic-embed-text`
  Pull if missing: `ollama pull nomic-embed-text`
NOTE
}
