#!/usr/bin/env bats
# tests/install/antigravity-adapter.bats
#
# Verifies the --antigravity-rules opt-in flag in install.sh.
# Spec: docs/specs/antigravity-adapter.md
# Sister test: tests/install/cursor-adapter.bats (#163)
#
# Closes #190.
#
# Critical guards:
#   - Adapter is PROJECT-SCOPED at <repo>/.agent/rules/walter-os.md
#     (NOT ~/.agent/ — never touches user-scope).
#   - GEMINI.md collision warning surfaces, but does not fail the build
#     (operator may legitimately have a GEMINI.md they want to keep).
#   - Generator errors with exit 2 + clear message when AGENTS.md
#     is missing (the cascade is the source of truth).

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
  INSTALL_SH="$REPO_ROOT/install.sh"
  export WALTER_OS_HOME="$REPO_ROOT"
  FAKE_REPO="$BATS_TEST_TMPDIR/fake-repo"
  mkdir -p "$FAKE_REPO"
  cat > "$FAKE_REPO/AGENTS.md" <<'EOF'
# AGENTS.md — test fixture

## Universal disciplines

Test fixture content for the bats suite.
EOF
}

_run_antigravity_rules() {
  (
    cd "$FAKE_REPO"
    DRY_RUN=0 CHECK_ONLY=0 UPGRADE=0 UNINSTALL=0 STEP_ONLY="" \
      bash "$INSTALL_SH" --antigravity-rules
  )
}

_run_antigravity_rules_dry() {
  (
    cd "$FAKE_REPO"
    DRY_RUN=1 CHECK_ONLY=0 UPGRADE=0 UNINSTALL=0 STEP_ONLY="" \
      bash "$INSTALL_SH" --antigravity-rules --dry-run
  )
}

# ---------------------------------------------------------------------------
# AC-1, AC-2: produce a project-local .agent/rules/walter-os.md
# ---------------------------------------------------------------------------

@test "AC-1: install.sh --antigravity-rules produces project-local .agent/rules/walter-os.md" {
  run _run_antigravity_rules
  [[ "$status" -eq 0 ]]
  [[ -f "$FAKE_REPO/.agent/rules/walter-os.md" ]]
}

@test "AC-1 (regression guard): adapter NEVER writes to user-scope ~/.agent/" {
  # If the function ever regresses to user-scope, this test catches it.
  local user_target="$HOME/.agent/rules/walter-os.md"
  local before_mtime="(absent)"
  [[ -f "$user_target" ]] && before_mtime="$(stat -f %m "$user_target" 2>/dev/null || stat -c %Y "$user_target")"

  run _run_antigravity_rules
  [[ "$status" -eq 0 ]]

  local after_mtime="(absent)"
  [[ -f "$user_target" ]] && after_mtime="$(stat -f %m "$user_target" 2>/dev/null || stat -c %Y "$user_target")"
  [[ "$before_mtime" == "$after_mtime" ]]
}

@test "AC-2: adapter file contains the AGENTS.md body + SHA trailer" {
  run _run_antigravity_rules
  [[ "$status" -eq 0 ]]
  local md="$FAKE_REPO/.agent/rules/walter-os.md"
  grep -q "Test fixture content for the bats suite" "$md"
  grep -qE '<!-- agents-md-sha256: [0-9a-f]{64} -->' "$md"
  # Header must explain the file is generated.
  grep -qiE "generated by walter-os install\\.sh --antigravity-rules" "$md"
  # And NOT have Cursor's MDC frontmatter — plain markdown for Antigravity.
  ! head -3 "$md" | grep -qE "^---$"
}

# ---------------------------------------------------------------------------
# AC-3: error when AGENTS.md is missing
# ---------------------------------------------------------------------------

@test "AC-3: fails with exit 2 when AGENTS.md is missing" {
  rm -f "$FAKE_REPO/AGENTS.md"
  run _run_antigravity_rules
  [[ "$status" -eq 2 ]]
  [[ "$output" == *"No AGENTS.md"* ]]
  [[ ! -d "$FAKE_REPO/.agent" ]]
}

# ---------------------------------------------------------------------------
# AC-4: warn (don't fail) when GEMINI.md exists
# ---------------------------------------------------------------------------

@test "AC-4: warns when GEMINI.md exists but still generates the adapter" {
  echo "# Stray GEMINI" > "$FAKE_REPO/GEMINI.md"
  run _run_antigravity_rules
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"GEMINI.md"* ]]
  [[ "$output" == *"shadow"* ]] || [[ "$output" == *"precedence"* ]]
  # Adapter still produced.
  [[ -f "$FAKE_REPO/.agent/rules/walter-os.md" ]]
}

# ---------------------------------------------------------------------------
# AC-5: dry-run honoured
# ---------------------------------------------------------------------------

@test "AC-5: --dry-run --antigravity-rules does not write any files" {
  run _run_antigravity_rules_dry
  [[ "$status" -eq 0 ]]
  [[ ! -d "$FAKE_REPO/.agent" ]]
  [[ "$output" == *"would"* ]] || [[ "$output" == *"DRY"* ]] || [[ "$output" == *"mkdir"* ]]
}

# ---------------------------------------------------------------------------
# AC-11: idempotency
# ---------------------------------------------------------------------------

@test "AC-11: running --antigravity-rules twice produces identical file content" {
  run _run_antigravity_rules
  [[ "$status" -eq 0 ]]
  local md="$FAKE_REPO/.agent/rules/walter-os.md"
  local first_sha
  if command -v sha256sum >/dev/null 2>&1; then
    first_sha="$(sha256sum "$md" | awk '{print $1}')"
  else
    first_sha="$(shasum -a 256 "$md" | awk '{print $1}')"
  fi

  run _run_antigravity_rules
  [[ "$status" -eq 0 ]]
  local second_sha
  if command -v sha256sum >/dev/null 2>&1; then
    second_sha="$(sha256sum "$md" | awk '{print $1}')"
  else
    second_sha="$(shasum -a 256 "$md" | awk '{print $1}')"
  fi

  [[ "$first_sha" == "$second_sha" ]]
}

# ---------------------------------------------------------------------------
# AC-2 (extra): the SHA trailer matches the AGENTS.md content hash
# ---------------------------------------------------------------------------

@test "AC-2: recorded sha256 trailer matches the source AGENTS.md hash" {
  run _run_antigravity_rules
  [[ "$status" -eq 0 ]]
  local md="$FAKE_REPO/.agent/rules/walter-os.md"

  local agents_sha recorded_sha
  if command -v sha256sum >/dev/null 2>&1; then
    agents_sha="$(sha256sum "$FAKE_REPO/AGENTS.md" | awk '{print $1}')"
  else
    agents_sha="$(shasum -a 256 "$FAKE_REPO/AGENTS.md" | awk '{print $1}')"
  fi

  recorded_sha="$(grep -oE 'agents-md-sha256: [0-9a-f]{64}' "$md" | awk '{print $2}' | head -1)"
  [[ "$agents_sha" == "$recorded_sha" ]]
}
