#!/usr/bin/env bats
# tests/install/cursor-adapter.bats
#
# Verifies the --cursor-rules opt-in flag in install.sh.
# Spec: docs/specs/cursor-adapter-completion.md
# Plan: docs/specs/cursor-adapter-completion.plan.md
#
# Critical guard: the adapter must be PROJECT-SCOPED. Cursor reads MDC
# rules from <repo>/.cursor/rules/, NOT from ~/.cursor/. Tests use a
# temp directory as a fake repo and verify (a) the file lands in the
# temp dir, and (b) the operator's real ~/.cursor/ is never touched.

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
  INSTALL_SH="$REPO_ROOT/install.sh"
  # Match the WALTER_OS_HOME convention used by tests/cli/*.bats. install.sh
  # itself doesn't read WALTER_OS_HOME, but if the generator ever shells out
  # to bin/walter-os in the future, the env var will be set correctly.
  export WALTER_OS_HOME="$REPO_ROOT"
  # Use BATS_TEST_TMPDIR as the fake project root.
  FAKE_REPO="$BATS_TEST_TMPDIR/fake-repo"
  mkdir -p "$FAKE_REPO"
  # Synthesize a minimal AGENTS.md so the generator has source content.
  cat > "$FAKE_REPO/AGENTS.md" <<'EOF'
# AGENTS.md — test fixture

## Universal disciplines

Test fixture content for the bats suite.
EOF
}

# Run install.sh --cursor-rules with CWD set to the fake repo.
# Returns the file content on stdout; the test asserts on $output / $status.
_run_cursor_rules() {
  (
    cd "$FAKE_REPO"
    DRY_RUN=0 CHECK_ONLY=0 UPGRADE=0 UNINSTALL=0 STEP_ONLY="" \
      bash "$INSTALL_SH" --cursor-rules
  )
}

@test "AC-1: install.sh --cursor-rules produces project-local .cursor/rules/walter-os.mdc" {
  run _run_cursor_rules
  [[ "$status" -eq 0 ]]
  [[ -f "$FAKE_REPO/.cursor/rules/walter-os.mdc" ]]
}

@test "AC-1 (regression guard): adapter NEVER writes to user-scope ~/.cursor/" {
  # If the function ever regresses to user-scope, this test catches it. We
  # snapshot ~/.cursor/rules/walter-os.mdc state before + after and assert
  # the function did not create or modify it.
  local user_target="$HOME/.cursor/rules/walter-os.mdc"
  local before_mtime="(absent)"
  [[ -f "$user_target" ]] && before_mtime="$(stat -f %m "$user_target" 2>/dev/null || stat -c %Y "$user_target")"

  run _run_cursor_rules
  [[ "$status" -eq 0 ]]

  local after_mtime="(absent)"
  [[ -f "$user_target" ]] && after_mtime="$(stat -f %m "$user_target" 2>/dev/null || stat -c %Y "$user_target")"

  [[ "$before_mtime" == "$after_mtime" ]]
}

@test "AC-1: generated MDC file has the required header comment" {
  _run_cursor_rules
  grep -q "Generated by walter-os install.sh --cursor-rules" \
    "$FAKE_REPO/.cursor/rules/walter-os.mdc"
}

@test "AC-1: generated MDC file has the do-not-edit footer" {
  _run_cursor_rules
  grep -q "do not edit manually" \
    "$FAKE_REPO/.cursor/rules/walter-os.mdc"
}

@test "AC-1: generated MDC file has YAML frontmatter (description + globs + alwaysApply)" {
  _run_cursor_rules
  local mdc="$FAKE_REPO/.cursor/rules/walter-os.mdc"
  # First line of file must be the frontmatter delimiter.
  head -1 "$mdc" | grep -q '^---$'
  grep -q '^description: Walter-OS agent discipline contract' "$mdc"
  grep -q '^globs: \["\*\*/\*"\]' "$mdc"
  grep -q '^alwaysApply: true' "$mdc"
}

@test "AC-1: generated MDC file records the AGENTS.md content hash for staleness detection" {
  _run_cursor_rules
  grep -qE "agents-md-sha256: [0-9a-f]{64}" \
    "$FAKE_REPO/.cursor/rules/walter-os.mdc"
}

@test "AC-2: install.sh --cursor-rules is idempotent (second run produces identical output)" {
  _run_cursor_rules
  local first_hash
  first_hash="$(shasum -a 256 "$FAKE_REPO/.cursor/rules/walter-os.mdc" | awk '{print $1}')"

  _run_cursor_rules
  local second_hash
  second_hash="$(shasum -a 256 "$FAKE_REPO/.cursor/rules/walter-os.mdc" | awk '{print $1}')"

  [[ "$first_hash" == "$second_hash" ]]
}

@test "AC-1: --cursor-rules errors out when AGENTS.md is absent" {
  # Remove the synthesized AGENTS.md from setup.
  rm -f "$FAKE_REPO/AGENTS.md"
  run _run_cursor_rules
  [[ "$status" -ne 0 ]]
  [[ "$output" =~ "AGENTS.md" ]]
}

@test "AC-1 (dry-run): --dry-run does NOT create the .cursor directory" {
  run bash -c '
    cd "'"$FAKE_REPO"'"
    DRY_RUN=1 CHECK_ONLY=0 UPGRADE=0 UNINSTALL=0 STEP_ONLY="" \
      bash "'"$INSTALL_SH"'" --cursor-rules --dry-run
  '
  [[ "$status" -eq 0 ]]
  [[ ! -d "$FAKE_REPO/.cursor" ]]
}

@test "AC-1: --cursor-rules sets the flag (definition exists in install.sh)" {
  grep -q 'CURSOR_RULES_ONLY=1' "$INSTALL_SH"
  grep -q -- '--cursor-rules' "$INSTALL_SH"
}

@test "AC-1: generator function exists in install.sh" {
  grep -q '^generate_cursor_adapter()' "$INSTALL_SH"
}
