#!/usr/bin/env bats
# Tests that install.sh registers the expected PreToolUse hook chain in
# the generated ~/.claude/settings.json. Codex R2 MEDIUM M2: the previous
# template was missing approval-gate.sh, leaving destructive-op protection
# disabled.

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
}

@test "install.sh PreToolUse Bash chain includes bash-denylist.sh" {
  # We grep the install.sh source for the literal chain entry. The settings
  # are generated by jq inline so a textual match on install.sh is the
  # stable surface (vs running install.sh under HOME=$tmp and parsing JSON,
  # which is much heavier).
  grep -q 'hooks/bash-denylist.sh' "$REPO_ROOT/install.sh"
}

@test "M2: install.sh PreToolUse Bash chain includes approval-gate.sh" {
  # The comment in install.sh claims bash-denylist runs before approval-gate,
  # but approval-gate was missing from the chain entirely (Codex R2 M2).
  # This test pins it in place so it cannot regress silently.
  grep -q 'hooks/approval-gate.sh' "$REPO_ROOT/install.sh"
}

@test "M2: approval-gate.sh appears after bash-denylist.sh in the chain" {
  # Order matters: bash-denylist is cheap and fails fast on RCE injection;
  # approval-gate is heavier and decides destructive-op approval. The
  # in-code comment documents this ordering — verify the source matches.
  denylist_line=$(grep -n 'hooks/bash-denylist.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  approval_line=$(grep -n 'hooks/approval-gate.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  [ -n "$denylist_line" ]
  [ -n "$approval_line" ]
  [ "$denylist_line" -lt "$approval_line" ]
}

# ---------------------------------------------------------------------------
# OSS Trust A-2 (#122): default-deny network egress hook must be in the
# chain after approval-gate.sh. Without this pin the hook ships but is
# INERT — an operator-visible bug.
# ---------------------------------------------------------------------------

@test "AC-5 (#122 A-2): install.sh PreToolUse Bash chain includes network-gate.sh" {
  grep -q 'hooks/network-gate.sh' "$REPO_ROOT/install.sh"
}

@test "AC-5 (#122 A-2): network-gate.sh runs AFTER approval-gate.sh" {
  # bash-denylist → approval-gate → network-gate ordering: cheap regex
  # block first, destructive-op gate second, host check last (the host
  # check needs to source the loader + parse the command — heaviest of
  # the three).
  approval_line=$(grep -n 'hooks/approval-gate.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  network_line=$(grep -n 'hooks/network-gate.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  [ -n "$approval_line" ]
  [ -n "$network_line" ]
  [ "$approval_line" -lt "$network_line" ]
}

@test "AC-3 (#122 capability): install.sh PreToolUse Bash chain includes capability-check.sh" {
  grep -q 'hooks/capability-check.sh' "$REPO_ROOT/install.sh"
}

@test "AC-3 (#122 capability): capability-check.sh runs AFTER approval-gate.sh" {
  approval_line=$(grep -n 'hooks/approval-gate.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  cap_line=$(grep -n 'hooks/capability-check.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  [ -n "$approval_line" ]
  [ -n "$cap_line" ]
  [ "$approval_line" -lt "$cap_line" ]
}

@test "AC-3 (#122 capability): capability-check.sh runs BEFORE network-gate.sh" {
  cap_line=$(grep -n 'hooks/capability-check.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  network_line=$(grep -n 'hooks/network-gate.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  [ -n "$cap_line" ]
  [ -n "$network_line" ]
  [ "$cap_line" -lt "$network_line" ]
}

@test "AC-3 (#122 capability): edit hook matcher includes MultiEdit" {
  grep -q 'matcher: "Write|Edit|MultiEdit|NotebookEdit"' "$REPO_ROOT/install.sh"
}

@test "AC-5 (#122 A-2): network-gate.sh appears BEFORE branch-flow-guard.sh" {
  # branch-flow-guard is about push-target policy, which only matters
  # for git pushes that ALREADY passed the network-gate host check.
  # Keeping the network gate before the branch gate means an attempted
  # push to a disallowed host fails on the cheaper / more universal
  # check first.
  network_line=$(grep -n 'hooks/network-gate.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  branchflow_line=$(grep -n 'hooks/branch-flow-guard.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  [ -n "$network_line" ]
  [ -n "$branchflow_line" ]
  [ "$network_line" -lt "$branchflow_line" ]
}

@test "AC-2 (#122 A-4): install.sh registers session-timeout UserPromptSubmit hook" {
  grep -q 'UserPromptSubmit' "$REPO_ROOT/install.sh"
  grep -q 'hooks/session-timeout.sh' "$REPO_ROOT/install.sh"
}
