#!/usr/bin/env bats
# Tests that install.sh registers the expected PreToolUse hook chain in
# the generated ~/.claude/settings.json. Codex R2 MEDIUM M2: the previous
# template was missing approval-gate.sh, leaving destructive-op protection
# disabled.

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
}

@test "install.sh PreToolUse Bash chain includes bash-denylist.sh" {
  # We grep the install.sh source for the literal chain entry. The settings
  # are generated by jq inline so a textual match on install.sh is the
  # stable surface (vs running install.sh under HOME=$tmp and parsing JSON,
  # which is much heavier).
  grep -q 'hooks/bash-denylist.sh' "$REPO_ROOT/install.sh"
}

@test "M2: install.sh PreToolUse Bash chain includes approval-gate.sh" {
  # The comment in install.sh claims bash-denylist runs before approval-gate,
  # but approval-gate was missing from the chain entirely (Codex R2 M2).
  # This test pins it in place so it cannot regress silently.
  grep -q 'hooks/approval-gate.sh' "$REPO_ROOT/install.sh"
}

@test "M2: approval-gate.sh appears after bash-denylist.sh in the chain" {
  # Order matters: bash-denylist is cheap and fails fast on RCE injection;
  # approval-gate is heavier and decides destructive-op approval. The
  # in-code comment documents this ordering — verify the source matches.
  denylist_line=$(grep -n 'hooks/bash-denylist.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  approval_line=$(grep -n 'hooks/approval-gate.sh' "$REPO_ROOT/install.sh" \
    | grep -v '^[[:space:]]*#' | head -1 | cut -d: -f1)
  [ -n "$denylist_line" ]
  [ -n "$approval_line" ]
  [ "$denylist_line" -lt "$approval_line" ]
}
